<a href="https://colab.research.google.com/github/anasarshad7677-netizen/Complete-ML-repo/blob/main/1_working_with_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd

loading a csv file from the system

In [16]:
df = pd.read_csv('/content/students_1000.csv' , index_col='Student_ID')

In [17]:
df.head()

,Name,Gender,Age,University,Program,City,Semester,Matric_Percentage,12th_Marks_Percentage,IELTS_Score,CGPA,Attendance_Percentage,Projects_Completed
Student_ID,,,,,,,,,,,,,
STU0001,Emily Moore,Female,18,University of Karachi,BS Software Engineering,Islamabad,7,70,64,5.5,2.38,94,0
STU0002,Mitchell Sanchez,Male,21,Superior University,BS Software Engineering,Peshawar,4,87,88,5.1,2.56,94,3
STU0003,Sylvia Johnson,Male,18,Kinnaird College,BS Data Science,Islamabad,2,82,71,6.0,2.59,81,3
STU0004,Phillip Cooper,Female,23,University of the Punjab,BS Cyber Security,Islamabad,5,57,79,6.9,3.95,84,6
STU0005,Andrea Brown,Male,21,University of Karachi,BS Cyber Security,Rawalpindi,2,57,92,5.8,2.72,65,3

In [13]:
df = pd.read_csv('/content/students_1000.csv' , usecols =['Program','City','University'])

In [14]:
df.head()

                 University                  Program        City
0     University of Karachi  BS Software Engineering   Islamabad
1       Superior University  BS Software Engineering    Peshawar
2          Kinnaird College          BS Data Science   Islamabad
3  University of the Punjab        BS Cyber Security   Islamabad
4     University of Karachi        BS Cyber Security  Rawalpindi

Loading data directly in a csv file using the url and request method

In [10]:
import requests
from io import StringIO
URL = "https://www.kaggle.com/datasets/datascikhan/e-commerce-sales-and-customer-analytics"
headers = { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) ..."}
req  = requests.get(URL, headers=headers)
data = StringIO(req.text)
pd.read_csv(data)

<_io.StringIO object at 0x7a2e67d7a080>

squeeze function

In [22]:
pd.read_csv(
    '/content/students_1000.csv',
            usecols=['Age']
    )

     Age
0     18
1     21
2     18
3     23
4     21
..   ...
995   23
996   19
997   21
998   19
999   20

[1000 rows x 1 columns]

In [23]:
pd.read_csv(
    '/content/students_1000.csv',
      nrows=100
    )

,Student_ID,Name,Gender,Age,University,Program,City,Semester,Matric_Percentage,12th_Marks_Percentage,IELTS_Score,CGPA,Attendance_Percentage,Projects_Completed
0,STU0001,Emily Moore,Female,18,University of Karachi,BS Software Engineering,Islamabad,7,70,64,5.5,2.38,94,0
1,STU0002,Mitchell Sanchez,Male,21,Superior University,BS Software Engineering,Peshawar,4,87,88,5.1,2.56,94,3
2,STU0003,Sylvia Johnson,Male,18,Kinnaird College,BS Data Science,Islamabad,2,82,71,6.0,2.59,81,3
3,STU0004,Phillip Cooper,Female,23,University of the Punjab,BS Cyber Security,Islamabad,5,57,79,6.9,3.95,84,6
4,STU0005,Andrea Brown,Male,21,University of Karachi,BS Cyber Security,Rawalpindi,2,57,92,5.8,2.72,65,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,STU0096,Emma Gordon,Female,25,University of Karachi,BS Software Engineering,Rawalpindi,6,72,52,7.4,2.59,88,0
96,STU0097,Courtney Deleon,Male,23,University of Karachi,BS Cyber Security,Islamabad,4,80,67,5.7,2.42,89,5
97,STU0098,Jennifer James,Female,18,University of Karachi,BS Computer Science,Rawalpindi,4,70,58,7.8,2.57,95,6
98,STU0099,Pamela Simpson,Male,20,COMSATS University Islamabad,BS Cyber Security,Islamabad,1,72,59,8.5,3.17,71,1
99,STU0100,Casey Barber,Female,21,Superior University,BS Cyber Security,Sialkot,2,56,61,5.9,2.43,86,5